project:
  type: website
  output-dir: docs

website:
  title: "2024_r_stats"
  navbar:
    left:
      - href: scripts/index.qmd
        text: Home
      - scripts/about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

